# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keep_files: [css, js, img]
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
paginate: 10
paginate_path: "/journal/page/:num/"
permalink: "/journal/:title"

# Build settings
markdown: kramdown

collections:
  works:
    output: true
    permalink: /work/:path/
  writings:
    output: true
    permalink: /writing/:path/

defaults:
  -
    scope:
      path: ""
      type: works
    values:
      layout: work
  -
    scope:
      path: ""
      type: writings
    values:
      layout: writing
